### ISSUE TITLE
but where is pytorch code , as you wrote in paper

### ISSUE THREAD

**Issue by Sandy4321** [DevSinghSachan/investigating-text-classifiers#1]
thanks for code
but where is pytorch code , as you wrote in paper
For neural network models, we have a common experimental setup based on Pytorch
framework (Paszke et al., 2017) for all the datasets unless specified otherwise

**Comment by DevSinghSachan** [comment]
For the Neural Net LSTM and CNN approaches, we made use of the models implemented in the baseline repo: https://github.com/dpressel/baseline
One option is that you can extend the datasets.json file with the path of the datasets included in this repo:
https://github.com/dpressel/baseline/blob/master/python/mead/config/datasets.json
 and then use one of the example config files such as https://github.com/dpressel/baseline/blob/master/python/mead/config/sst2-lstm-pyt.yml 
with the dataset name changes. You should be getting similar scores for the random and lexicon-based splits in the paper. 
Let me know in case of any issues.

**Comment by Sandy4321** [comment]
great thanks for soon answer
is it difficult to specify what .yml files exactly you used for paper
since there are many different, for example https://github.com/dpressel/baseline/blob/master/python/mead/config/sst2-nbow-keras.yml

**Comment by DevSinghSachan** [comment]
You can try to make use of this config file for aclImdb experiments on LSTM encoder
```
{
    "task": "classify",
    "batchsz": 25,
    "basedir": "./aclimdb-lstm",
    "features": [
        {
            "name": "word",
            "vectorizer": { "type": "token1d" },
            "embeddings": { "label": "glove-840B" }
        }
    ],
    "preproc": {
        "mxlen": 500,
        "clean": true,
        "min_f": 2
    },
    "backend": "pytorch",
    "dataset": "aclimdb_lexicon",
    "loader": {
        "reader_type": "default"
    },
    "unif": 0.25,
    "model": {
        "model_type": "lstm",
        "rnn_type": "lstm",
        "hsz": 512,
        "dropout": 0.2,
        "finetune": true
    },
    "train": {
        "epochs": 10,
        "optim": "adam",
        "eta": 0.001,
        "weight_decay": 0.0,
        "early_stopping_metric": "acc"
    }
}
```
